version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  www:
    depends_on:
      - mysql
    restart: always
    links:
      - mysql
    image: iget/default-www
    volumes:
      - /c/wordpress-environment/www:/var/www/
    ports:
      - "8888:80"
  phpmyadmin:
    depends_on:
      - mysql
    restart: always
    links:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    ports:
      - "8889:80"

volumes:
  mysql_data:
    driver: local
