version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  www:
    depends_on:
      - mysql
    restart: always
    links:
      - mysql
    build: images/www
    image: wordpress-www
    volumes:
      - ../www:/var/www/
    ports:
      - "8888:80"

volumes:
  storage:
    driver: local
  mysql_data:
    driver: local